name: beavercash
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # More compatible SDK range

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  google_fonts: ^6.2.1
  http: ^1.0.0
  logging: ^1.2.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  cloud_firestore: ^5.6.5
  username_generator: ^1.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - lib/images/
